version: '3.5'
services:

        main:
                build:
                        context: main
                container_name: main
                restart: always
                networks:
                        - frontmulti
networks:
    frontmulti:
                external:
                        name: frontmulti